### Obtener todos
GET http://localhost:3000/code

### Obtener por id
GET http://localhost:3000/code/2

### Agregar
POST http://localhost:3000/code
Content-Type: application/json

{
    "name": "Código de prueba"
}


### Eliminar
DELETE http://localhost:3000/code/
Content-Type: application/json

{
    "ids": [1]
}


### Actualizar nombre
PATCH  http://localhost:3000/code/3
Content-Type: application/json

{
    "name": "Código actualizado"
}