### Obtener todos
GET http://localhost:3000/department

### Obtener por id
GET http://localhost:3000/department/1

### Agregar
POST http://localhost:3000/department
Content-Type: application/json

{
    "name": "Departamento 1"
}


### Eliminar
DELETE http://localhost:3000/department/
Content-Type: application/json

{
    "ids": [1]
}


### Actualizar nombre
PATCH  http://localhost:3000/department/1
Content-Type: application/json

{
    "name": "Unidad nuevo nombre"
}