### Obtener todos
GET http://localhost:3000/product

### Obtener por id
GET http://localhost:3000/product/1

### Agregar
POST http://localhost:3000/product
Content-Type: application/json

{
    "id_department": 1,
    "id_supplier": 1,
    "amount": 100,
    "buy": 100,
    "min": 5,
    "refundable": true,
    "codes": [
        {
            "id": 1,
            "code": "Código 1"
        },
        {
            "id": 2,
            "code": "Código 2"
        }
    ],
    "sales": [{
        "id_unit": 1,
        "sale": 100,
        "profit": 10
    },
    {
        "id_unit": 1,
        "sale": 200
    }],
    "name": "Pza"
}


### Eliminar
DELETE http://localhost:3000/product/
Content-Type: application/json

{
    "ids": [1]
}


### Actualizar nombre
PATCH  http://localhost:3000/product/1
Content-Type: application/json

{
    "name": "Unidad nuevo nombre"
}