PATCH http://localhost:3000/user/shortcuts
Content-Type: application/json

{
    "shortcuts": [
        { "id": 1 ,"shortcut":	"ctrl+t" },
        { "id": 2 ,"shortcut":	"alt+t" },
        { "id": 3 ,"shortcut":	"ctrl+shift+t" },
        { "id": 4 ,"shortcut":	"ctrl+z" },
        { "id": 5 ,"shortcut":	"alt+z" },
        { "id": 6 ,"shortcut":	"ctrl+shift+z" },
        { "id": 7 ,"shortcut":	"alt+c" },
        { "id": 8 ,"shortcut":	"alt+e" },
        { "id": 9 ,"shortcut":	"alt+r" },
        { "id": 10 ,"shortcut":	"alt+p" },
        { "id": 11 ,"shortcut":	"alt+a" },
        { "id": 12 ,"shortcut":	"alt+k" },
        { "id": 13 ,"shortcut":	"ctrl+space" },
        { "id": 14 ,"shortcut":	"alt+l" },
        { "id": 15 ,"shortcut":	"alt+x" },
        { "id": 16 ,"shortcut":	"alt+m" },
        { "id": 17 ,"shortcut":	"F1" },
        { "id": 18 ,"shortcut":	"F2" },
        { "id": 19 ,"shortcut":	"F3" },
        { "id": 20 ,"shortcut":	"F4" },
        { "id": 21 ,"shortcut":	"F5" },
        { "id": 22 ,"shortcut":	"F6" },
        { "id": 23 ,"shortcut":	"F7" }
    ],
    "username": "Administrador"
}