### Obtener todos
GET http://localhost:3000/user

### Obtener por id
GET http://localhost:3000/user/1

### Agregar
POST http://localhost:3000/user
Content-Type: application/json

{
    "id_user_type": 2,
    "name": "aldo 2",
    "password": "Contrasenia"
}


### Eliminar
DELETE http://localhost:3000/user
Content-Type: application/json

{
    "ids": [2,3]
}


### Actualizar 
PATCH  http://localhost:3000/user/1
Content-Type: application/json

{
    "id_user_type": 1,
    "name": "root",
    "password": "Contrasenia"
}