### Obtener todos
GET http://localhost:3000/entity_type

### Obtener por id
GET http://localhost:3000/entity_type/1

### Agregar
POST http://localhost:3000/entity_type
Content-Type: application/json

{
    "name": "Proveedor",
    "username": "Administrador"
}


### Eliminar
DELETE http://localhost:3000/entity_type/
Content-Type: application/json

{
    "ids": [1],
    "username": "Administrador"
}


### Actualizar nombre
PATCH  http://localhost:3000/entity_type/1
Content-Type: application/json

{
    "name": "Cliente",
    "username": "Administrador"
}